/*
 * ARMADILHAS BEM CONHECIDAS DA ORIENTAÇÃO A OBJETOS
 * */

// GRANULARIDADE DE CLASSES EXTREMA
// EMPREGO DE HERANÇA AO INVÊS DE COMPOSIÇÃO
// EXECUTAR MÉTODOS SOBRESCRITÍVEIS EM CONSTRUTORES
// OBJETOS DEUS - CLASSES QUE FAZEM TUDO OU QUASE
// SUPER-ACOPLAMENTO - CLASSES COM ALTO NÍVEL DE DEPENDÊNCIA
// USO EXCESSIVO DE ENGENHARIA (PADRÕES) - MATAR FORMIGA COM BAZUCA
// ABSTRAÇÕES DE EXISTÊNCIA DESNECESSÁRIA - A INTERFACE QUE NUNCA FOI UTILIZADA EM OUTROS CONTEXTOS
// ENCAPSULAMENTO INEFICAZ - CLASSES COM COMPORTAMENTO E ATRIBUTOS VAZANDO PARA OUTRAS PARTES

/* Mitigação
 * -Aplicar princípios SOLID
 * -Aplicar princípio Keep It Simple Supid
 * -Implementar testes automatizados de unidade e integração
 * -Estudar usos indevidos de padrões de projeto
 * */
